from decimal import Decimal
'''a=input("Enter your name:" )
b=input("Enter your D.O.B:" )
c=input("Enter your ID:" )
d=input("Enter your Phone no:")
e=int(input("Enter your age:" ))
f=int(input("Enter your marks:" ))
print("Name is;",a)
print("D.O.B is:",b)
print("ID is:",c)
print("Phone no is:",d)
print("Age is:",e)
print("Marks is:",f)
'''
a=Decimal(0.1)-Decimal(0.1)
print(float(a))